name: PyDependency builder

on:
  workflow_dispatch:
  push:
    paths:
      - 'pydependencies/**'
      - '!pydependencies/tests/**'
    branches:
      - main

jobs:
  pydependencies-image-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./pydependencies
          file: pydependencies/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/pydependencies:latest
